#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TwilioClientTest.Android.Resource", IsApplication=true)]

namespace TwilioClientTest.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int callOptionsLabel = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int connectionStatus = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int connectionStatusText = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int deviceListening = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int deviceListeningLabel = 2131099668;
			
			// aapt resource value: 0x7f060007
			public const int deviceStatus = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int deviceStatusText = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int dialButton = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int disconnectLabel = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int disconnectSound = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int incomingLabel = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int incomingSound = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060013
			public const int muted = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int mutedLabel = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int optionsLabel = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int outgoingLabel = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int outgoingSound = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int soundsLabel = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int statusLabel = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int targetLabel = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int targetText = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int disconnect = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int incoming = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int outgoing = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int deviceListening = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int dial = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int disconnectSound = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int hangup = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int iWantThisToSayStuff = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int incomingSound = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int muted = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int options = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int outgoingSound = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ready = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
